- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    jenkins_hostname: jenkins.example.com
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      become: true
